### ISSUE TITLE
Keep getting following error.

### ISSUE THREAD

**Issue by thelazyb** [benthompson2001/Azure-Ethereum-mine#2]
ERROR: The Nouveau kernel driver is currently in use by your system.  This
         driver is incompatible with the NVIDIA driver, and must be disabled
         before proceeding.  Please consult the NVIDIA driver README and your
         Linux distribution's documentation for details on how to correctly
         disable the Nouveau kernel driver.

**Comment by BenedictThompson-zz** [comment]
Have you tried rebooting the VM?

**Comment by thelazyb** [comment]
Yes, a couple times. 
If I ignore this and try to start miner using -G i get no graphic card available with enough memory. 

~ Gaurave

**Comment by thelazyb** [comment]
Finally i got it working. I ran the driver installer without any options
and driver has a screen which helps to disable old driver.

**Comment by BenedictThompson-zz** [comment]
Nice
